import type { Metadata } from "next";
import { Geist, Geist_Mono, Audiowide } from "next/font/google";
import "./globals.css";

// import AOS from "aos";
// import "aos/dist/aos.css";
import { ThemeProvider } from "@/components/ThemeProvider/theme-provider";
import Navbar from "@/components/Navbar/Navbar";

const audiowide = Audiowide({ weight: '400', subsets: ['latin'], display: 'swap' })


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   AOS.init({
  //     duration: 800,
  //     once: true,
  //   });
  // }, []);
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${audiowide.className} ${geistSans.variable} ${geistMono.variable} antialiased bg-gaming-glow relative min-h-screen text-white`}
      >
        <div className="glow-overlay top-[30%] left-[50%]"></div>
        <div className="glow-overlay top-[80%] left-[20%]"></div>
        <div className="glow-overlay bottom-[10%] right-[30%]"></div>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          
            <Navbar />
          {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
